### PR TITLE
Accessibility improvement

### PR DESCRIPTION
**Pull request by hakloev**
# Why?

We got a feedback from a user saying that if no button to close the sheet was provided, it's impossible to close when using VoiceOver.

# What?

The main thing here is that the handle is made accessible and will dismiss the sheet if activated. With this PR, the handle will be the first element in the sheet to be read by VoiceOver. 

* Set `accessibilityViewIsModal = true` in `BottomSheetView` to stop VoiceOver from reading content behind the sheet
* Extract `handleView` from `BottomSheetView`, and create `HandleView` to be able to override `accessibilityActivate`
* Make `HandleView` accessible by setting `isAccessibilityElement = true` and `accessibilityTraits = .button`

**Localization**

* Add `Localizable.strings` for both English and Norwegian. I set the default localization of `Package.swift` to `en` as this is an open source project. Any objections? 

# Show me

| Before | After |
| --- | --- |
| Kapture 2020-11-23 at 10 27 47 | Kapture 2020-11-23 at 10 26 45 |

### CODE REVIEW

**Comment by ninarg** [comment]
Great work 👏  It's good to always have a fallback, we probably have some bottom sheets where we forgot to add a close button. I have one question, is the tappable area only the little gray handle button? I was wondering if if it's big enough to easily hit it 🤔

**Comment by hakloev** [comment]
The view itself is not tappable. When using VoiceOver a double tap anywhere on the screen will perform the action of the currently focused element.

**Comment by hakloev** [comment]
If you swipe left/right with two fingers you "slide" back and forth through all accessibility elements :) And then you can double tap the active one.

**Comment by ninarg** [comment]
Cool, will make sure to try that! 😁

**Pull request merged**
